### ISSUE TITLE
This player does not support this format is not updated

### ISSUE THREAD

**Issue by irakpro** [bharadwajpro/m3u8-player#3]
https://shahid03ak-a.akamaihd.net/c7eff0af-cd22-4226-9e85-e88e74b695e9/3000056542_TXMHD_Dai_Al_Komr_1_Ep__26_.ism/QualityLevels(4999998)/Manifest(video,format=m3u8-aapl-v3,audiotrack=audioname)

**Comment by bharadwajpro** [comment]
If you are still facing issues, can you provide a valid link?
