### ISSUE TITLE
Play in VLC?

### ISSUE THREAD

**Issue by LagradOst** [bharadwajpro/m3u8-player#4]
The player works great in browsers, BUT you can't play any "converted" link in vlc nor download them as an mp4. Im currently having a problem with a link that has small audio gaps because it is a m3u8 file and want to fix this. This is solved in your player, but it has the problems mentioned before. Is it possible to play a m3u8 file like an mp4 in vlc or download it directly? 

Do you have to download the entire video and convert it, for it to work in vlc?

**Comment by bharadwajpro** [comment]
When I tried VLC it was not that reliable for me, so I created this for myself by using external libraries and it worked fine. For downloading the video, you can use `ffmpeg`.
