### ISSUE TITLE
add button support for listing channels

### ISSUE THREAD

**Issue by d0n0t** [bharadwajpro/m3u8-player#6]
hmm

**Comment by bharadwajpro** [comment]
Can you be more specific?

**Comment by d0n0t** [comment]
button jaise ki pehle se hamane .m3u8 add kar rakha ho.yani indexing m3u8.

**Comment by d0n0t** [comment]
btw ,i found alternative way to do it.create a button n add player script with src"any.m3u8".thanxx btw for responding

**Comment by d0n0t** [comment]
can i close my issue??(if you have any telegram account lemme know)
