### ISSUE TITLE
I can't play the following link

### ISSUE THREAD

**Issue by Zero3K** [bharadwajpro/m3u8-player#7]
http://193.42.99.133:23455/TVTOKYO/playlist.m3u8

It just gives me a spinning circle.

**Comment by bharadwajpro** [comment]
This is served over `http`. So chrome will block this. You can either take my repo and host it in http server(not https) OR take an m3u8 URL served over `https`. For more details, see "Known Issues" in README.

**Comment by Zero3K** [comment]
Its no longer an issue since the m3u8 at the link has been removed and I am using a different way to watch TV Tokyo.
